const list = [
  {
    id: 1,
    title: "iphone 14",
    text:"Big and bigger.",
    price: 89,
    img: "https://pngimg.com/uploads/iphone_14/iphone_14_PNG20.png",
    amount: 1,
  },
  {
    id: 2,
    title: "Galaxy S22 Ultra",
    text: "The most impressive portrait mode photos I’ve seen from a smartphone yet.",
    price: 98,
    img: "https://images.samsung.com/in/smartphones/galaxy-s22-ultra/images/galaxy-s22-ultra_highlights_kv_img.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Samsung Crystal 4K UHD Smart TV",
    text: "Feel the reality of 4K UHD Resolution",
    price: 143,
    img: "https://images.samsung.com/is/image/samsung/p6pim/in/feature/164099569/in-feature-uhd-4k-tv-532635303?$FB_TYPE_A_JPG$",
    amount: 1,
  },
  {
    id: 4,
    title: "SAMSUNG",
    text: "	Samsung 692 litres Side-by-Side Refrigerator",
    price: 57,
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR4VHoXYs_LFRDT02ZNtr3LJgY1pglh3tWIsJDCAiaqnROlpK6QQtDa0uEsKBGYxM3LlgcIwW0DZDZEJypgXo-KyAsx26WYgbQmUWz4N0FKUp-IK9TQQL3G9A&usqp=CAE",
    amount: 1,
  },
  {
    id: 5,
    title: "B O A T",
    text: "From workouts to adventures, boAt will get you sailing!",
    price: 149,
    img: "http://cdn.shopify.com/s/files/1/0057/8938/4802/products/airdopes-121-v2-black.png?v=1612765376",
    amount: 1,
  },
  {
    id: 6,
    title: "O N E P L U S",
    text: "Evolve your digital life",
    price: 135,
    img: "https://static.digit.in/default/3b5f49c62912a8422a2a1e9578e3944d6961e4ba.jpeg?tr=w-600",
    amount: 1,
  },
  {
    id: 7,
    title: "Samsung Tablet ",
    text: "Galaxy Tab S8 Ultra Book Cover Keyboard",
    price: 693,
    img:" https://images.samsung.com/is/image/samsung/p6pim/in/ef-dx900ubngin/gallery/in-galaxy-tab-s8-ultra-bookcover-ef-dx900-ef-dx900ubngin-thumb-531215642?$216_216_PNG$",
    amount: 1,
  },
  {
    id: 8,
    title:"Galaxy Watch",
    text: "Galaxy Watch4 Classic",
    price: 289,
    img: "https://images.samsung.com/is/image/samsung/assets/in/2208/pcd/watches/Galaxy_Watch5Pro_PC.png?$376_376_PNG$",
    amount: 1,
  },
  {
    id: 9,
    title: "J B L",
    text: "Louder, more powerful sound.12 Hours of Playtime",
    price: 80,
    img: "https://in.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw1dfa5e81/1_JBL_FLIP6_HERO_BLACK_29391_x2.png?sw=537&sfrm=png",
    amount: 1,
  },
  {
    id: 10,
    title: "HP Laptop",
    text: "HP ZBook Firefly 16 G9 Mobile Workstation PC",
    price: 86,
    img: "https://in-media.apjonlinecdn.com/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/6/V/6V1U6PA-1_T1666145792.png",
    amount: 1,
  },
  {
    id: 11,
    title: "Galaxy Z Fold4",
    text: "The Z Fold4 is still unmatched in terms of productivity and multitasking.",
    price: 120,
    img: "https://images.samsung.com/in/smartphones/galaxy-z-fold4/images/galaxy-z-fold4_highlights_kv.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Redmi 11 Prime 5G",
    text: "Enjoy more with 5G No more waiting required",
    price: 157,
    img: "https://i02.appmifile.com/mi-com-product/fly-birds/redmi-11-prime-5g/img03.jpg?f=webp",
    amount: 1,
  },
];

export default list;